import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist_Mono, VT323, Oswald } from "next/font/google";
import { Toaster } from 'sonner'
import "./globals.css";
import clsx from "clsx";

const bytesized = localFont({
	src: "./fonts/Bytesized-Regular.ttf",
	weight: "400",
	variable: "--font-bytesized",
})

const geist = Geist_Mono({
	weight: "400",
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

const vt323 = VT323({
	weight: "400",
	variable: "--font-vt323",
	subsets: ["latin"],
})

const oswald = Oswald({
	weight: "400",
	variable: "--font-oswald",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={clsx(`font-vt323 antialiased`, bytesized.variable, geist.variable, vt323.variable, oswald.variable)}
			>
				<main className="container mb-12 max-w-3xl mx-auto px-2">
					<Toaster position="top-center" />
					{children}
				</main>
			</body>
		</html>
	);
}
